name: Asset size

on: [pull_request]

jobs:
  compare:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: chrysanthos/simple-asset-size-reporter@3c86a594c400b40a4ebe6418da605a5d2755ef52 # 1.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: '["dist/*.js"]'
          with-same: "false"
          build-assets: "npm run install-build"
